spring.application.name=kanban

# JDBC-Datenbank URI, Benutzer/Passwort setzen
spring.datasource.url=jdbc:h2:mem:kanbandb
spring.datasource.username=h2
spring.datasource.password=h2

# Automatisch Tabellen etc. aus Entities anlegen
spring.jpa.generate-ddl=true
# Bei jedem Anwendungsstart Datenbank droppen und frisch anlegen
# Im in-memory-Betrieb weniger interessant, spaeter mit DB-Dateien aber schon.
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type=INFO
logging.level.org.springframework.web.socket=DEBUG