package de.hsrm.master.concurrency.kanbanboard.stomp;

public enum WsEventType {
    BOARD_CREATED, BOARD_UPDATED, BOARD_DELETED, COLUMN_CREATED, COLUMN_UPDATED, COLUMN_DELETED, TASK_CREATED, TASK_UPDATED, TASK_MOVED, TASK_DELETED, PRESENCE_CHANGED, LOCK_CHANGED
}
